services:
  server:
    image: bitnami/laravel
    volumes:
      - ./backend:/app
    environment:
      - LARAVEL_DATABASE_HOST=database
      - LARAVEL_DATABASE_NAME=gallery-desktop-app
      - LARAVEL_DATABASE_USER=root
      - LARAVEL_DATABASE_PASSWORD=1234
      - LARAVEL_DATABASE_PORT_NUMBER=3306
    restart: always
    ports:
      - 8000:8000
    command: >
      sh -c "php artisan migrate --force &&
             /opt/bitnami/scripts/laravel/run.sh"

  database:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=gallery-desktop-app

  node-chat:
    image: node:18
    working_dir: /app
    volumes:
      - ./node-chat:/app
    ports:
      - 3001:3001
    command: sh -c "npm install && node server.js"
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=gallery-desktop-app
      - DB_PORT=3306
    depends_on:
      - database
